# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sample the number of days PAST plant death.
#'
#' @noRd
#'
NULL

#' Update Z and plant_days
#'
#' @noRd
#'
NULL

#' Replace plants
#'
#' @noRd
#'
NULL

#' Simulate one cage.
#'
#'
#' @noRd
#'
NULL

#' log(mortality) at a time x after plant death starts.
#'
#' Doing this here keeps from having to do this calculation many times.
#' `max_t` should be more than enough.
#'
#' @noRd
#'
NULL

#' Simulate multiple cages.
#'
#'
#' @inheritParams sim_cages
#'
#' @noRd
#'
#'
sim_cages_ <- function(n_cages, N_0, max_t, R, A, D_mat, process_error, plant_mort_0, plant_mort_1, plant_death_age_mean, plant_death_age_sd, repl_times, repl_age, extinct_N, n_cores, by_cage, show_progress) {
    .Call(`_cwsims_sim_cages_`, n_cages, N_0, max_t, R, A, D_mat, process_error, plant_mort_0, plant_mort_1, plant_death_age_mean, plant_death_age_sd, repl_times, repl_age, extinct_N, n_cores, by_cage, show_progress)
}

make_group_tree <- function(pBigMat, pool_sizes, n_reps, n_plants, max_t) {
    .Call(`_cwsims_make_group_tree`, pBigMat, pool_sizes, n_reps, n_plants, max_t)
}

save_group_tree <- function(pTree, filename) {
    .Call(`_cwsims_save_group_tree`, pTree, filename)
}

load_group_tree <- function(filename) {
    .Call(`_cwsims_load_group_tree`, filename)
}

view_tree_values <- function(pTree, level) {
    .Call(`_cwsims_view_tree_values`, pTree, level)
}

grouped_mean <- function(pBigMat, pTree, by_plant, by_date, zeros = FALSE, show_progress = TRUE) {
    .Call(`_cwsims_grouped_mean`, pBigMat, pTree, by_plant, by_date, zeros, show_progress)
}

