# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sample the number of days PAST plant death.
#'
#' @noRd
#'
NULL

#' Update Z and plant_days
#'
#' @noRd
#'
NULL

#' Replace plants
#'
#' @noRd
#'
NULL

#' Simulate one cage.
#'
#'
#' @noRd
#'
NULL

#' log(mortality) at a time x after plant death starts.
#'
#' Doing this here keeps from having to do this calculation many times.
#' `max_t` should be more than enough.
#'
#' @noRd
#'
NULL

#' Simulate multiple cages.
#'
#'
#' @inheritParams sim_cages
#'
#' @noRd
#'
#'
sim_cages_ <- function(n_cages, N_0, max_t, R, A, D_mat, process_error, plant_mort_0, plant_mort_1, plant_death_age_mean, plant_death_age_sd, repl_times, repl_age, extinct_N, n_cores, by_cage, show_progress) {
    .Call(`_cwsims_sim_cages_`, n_cages, N_0, max_t, R, A, D_mat, process_error, plant_mort_0, plant_mort_1, plant_death_age_mean, plant_death_age_sd, repl_times, repl_age, extinct_N, n_cores, by_cage, show_progress)
}

#' Mean by groups of columns of simulated aphid abundances.
#'
#' Note: It assumes the input matrix has the following columns (in order):
#' plant, line, date, N, pool, and rep.
#' It also assumes that the matrix is ordered by pool, rep, plant, line, then date.
#'
#'
#' @param pBigMat `big.matrix` object pointer (the `@address` slot!).
#' @param group_cols Vector of columns along which means will be calculated.
#' @param zeros Boolean for whether to compute the proportion of zeros rather than
#'     the mean. Defaults to `FALSE`.
#'
#' @export
#'
grouped_mean <- function(pBigMat, by_plant, by_date, zeros = FALSE, show_progress = TRUE) {
    .Call(`_cwsims_grouped_mean`, pBigMat, by_plant, by_date, zeros, show_progress)
}

