# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate one cage.
#'
#'
#' @noRd
#'
NULL

#' log(mortality) at a time x after plant death starts.
#'
#' Doing this here keeps from having to do this calculation many times.
#' max(`max_t`, `max_t - plant_death_age`) should be more than enough.
#'
#' @noRd
#'
NULL

#' Simulate multiple cages.
#'
#'
#' @inheritParams sim_cages
#'
#' @noRd
#'
#'
sim_cages_ <- function(n_cages, N_0, max_t, R, A, D_0, D_1, process_error, plant_mort_0, plant_mort_1, plant_death_age, repl_times, repl_plants, n_cores, show_progress) {
    .Call(`_cwsims_sim_cages_`, n_cages, N_0, max_t, R, A, D_0, D_1, process_error, plant_mort_0, plant_mort_1, plant_death_age, repl_times, repl_plants, n_cores, show_progress)
}

