source(".Rprofile")

suppressPackageStartupMessages({
    library(clonewars)
})



ggplot2::theme_set(
    theme_bw(base_family = "Helvetica", base_size = 12) +
        theme(plot.background = element_blank(),
              panel.grid = element_blank(),
              panel.background = element_blank(),
              panel.border = element_blank(),
              strip.background = element_blank(),
              strip.text = element_blank(),
              strip.placement = "outside",
              panel.spacing = unit(1.5, "lines"),
              legend.position = "right",
              legend.background = element_blank(),
              legend.text = element_text(size = 13),
              legend.text.align = 0,
              legend.key = element_blank(),
              axis.line.x = element_line(size = 0.4),
              axis.line.y.left = element_line(size = 0.4),
              axis.line.y.right = element_blank(),
              axis.ticks = element_blank(),
              axis.title = element_blank(),
              axis.text = element_blank())
)

# Palette generated by Material Palette - materialpalette.com/blue/deep-orange
palette <- list(
    dark_primary    = "#1976D2",
    default_primary = "#2196F3",
    light_primary   = "#BBDEFB",
    text_primary    = "#FFFFFF",
    accent          = "#FF5722",
    primary_text    = "#212121",
    secondary_text  = "#757575",
    divider         = "#BDBDBD"
)

# Palette for clonal lines ranging from palette$dark_primary to palette$accent using
# http://eyetracking.upol.cz/color/
line_palette <- c("#006cd1", "#5c6bbf", "#8069ad", "#9b679a", "#b56583",
                  "#cd626a", "#e45e4e", "#fd5826")
# To make colors red, blue, red, blue, ...
line_palette <- line_palette[c(1, 5, 2, 6, 3, 7, 4, 8)]

