---
title: "Choosing priors"
author: "Lucas A. Nell"
date: "2018-07-04"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Choosing priors}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dev = "svglite", 
  fig.width = 6,
  fig.height = 4,
  echo = FALSE
)
knitr::opts_knit$set(root.dir = normalizePath(".."))
options(tibble.print_min = 4L, tibble.print_max = 4L)
```


## Parameters

I estimated the following parameters in the model:

1. $\rho$ and $\sigma_\rho$, where $\sim \text{N}(\rho, \sigma_{\rho})$
    generates growth rates for each aphid line
2. $\phi$ and $\sigma_\phi$, where $\sim \text{N}(\phi, \sigma_{\phi})$ generates
    density dependences for each aphid line
3. $\sigma_{\varepsilon}$, where $\sim \text{N}(0, \sigma_{\varepsilon})$ generates
    process error for each observation
4. A vector of $\zeta$ values, one for each plant, that indicates
    the speed at which plant health deteriorates through time.


## Probability statements

I used the following probability statements for hyperparameters:

| Parameter            | Statement                           |
|:---------------------|------------------------------------:|
| $\rho$               | $\sim \text{N}(0,1)$                |
| $\sigma_\rho$        | $\sim \text{N}(0,1)\texttt{T[0,]}$  |
| $\phi$               | $\sim \text{N}(0,10)$               |
| $\sigma_\phi$        | $\sim \text{N}(0,10)\texttt{T[0,]}$ |
| $\sigma_\varepsilon$ | $\sim \text{N}(0,1)\texttt{T[0,]}$  |
| $\zeta$              | $\sim \text{N}(0,1)\texttt{T[0,]}$  |


Because I scaled the population abundances
(to have a mean of 0 and standard deviation of 1) before analyzing them in my model, I
could simply use standard normal distributions for most of my priors.
The only exception was for density dependence (parameters $\phi$ and $\sigma_\phi$).
Because the values were very near zero, I needed to make the generating
distribution flatter than standard normal.


