---
title: "Simulation description"
author: "Lucas A. Nell"
date: "2018-07-09"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Simulation description}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dev = "svglite", 
  fig.width = 6,
  fig.height = 4,
  echo = FALSE
)
```




This document outlines the structure of the simulations.



# Model description

Below is the model I'm simulating, for a given line and plant:

$$
\begin{align}
    N_{t+1} &= N_{t} ~ \text{e}^ {\rho + \varepsilon} + I - E \\
    \varepsilon &\sim \text{N}(0,\sigma^2_p) \\
\end{align}
$$

where... 

- $t$ indexes across time
- $N$ is aphid counts
- $\rho$ is the overall growth rate
- $\varepsilon$ is process error
- $I$ is the number of immigrants
- $E$ is the number of emigrants
- $\sigma_p$ is the standard deviation of the process error


The growth rate is determined by whether or not the plant is currently dying,
by population growth rate for a given line, and by the abundances and density dependences
of all lines on the focal plant:

$$
\begin{align}
    \rho_{ijt} &=
        \begin{cases}
            r_j \left( 1 - \alpha_j ~ Z_{it} \right), & \text{if}\ t < \gamma \\
            \log(m(t,\gamma)), & \text{otherwise} \\
        \end{cases} \\
    Z_{it} &= \sum^{n_l}_{j=1}{N_{ijt}} \\
    m(t,\gamma) &= \text{logit}^{-1}\left(  \beta_{0} + \beta_{1} ~ ( t - \gamma )
        \right) \\
    \gamma &\sim \text{N}(\mu_\gamma, \sigma^2_\gamma)
\end{align}
$$

where...

- $i$ indexes across plants
- $j$ indexes across aphid lines
- $r$ is the aphid line's growth rate
- $\alpha$ is the aphid line's density dependence
- $\gamma$ is the time at which a plant begins to die
- $m(t,\gamma)$ is the mortality rate caused by plant death, based on the number of days
  after it's started dying
- $n_l$ is the number of aphid lines
- $\beta_0$ and $\beta_1$ are the coefficients for the regression of the
  logit-transformed mortality rate on time since plant-death started
- $\mu_\gamma$ and $\sigma_\gamma$ are the mean and standard deviation of the
  distribution of the times at which plants begin to die



A Poisson distribution produces the numbers of aphids of line $j$ that
disperse from plant $i$ to all other plants (for receiving plant $k$, 
$d_{(i \rightarrow k)jt}$):

$$
\begin{align}
    \lambda_{ijt} &= \frac{ \delta_j ~ N_{ijt} }{ n_p }\\
    d_{(i \rightarrow k)jt} &\sim \text{Pois} ( \lambda_{ijt} )
\end{align}
$$

where $\delta_j$ is estimated from a Poisson GLM.
Note also that $d_{(i \rightarrow i)jt}$ is left at zero because dispersing back to
the same plant causes no net change.

I used these numbers to create two $n_l$ by $n_p$ matrices,
one for the number of immigrants ($\mathbf{I}$) and another for emigrants
($\mathbf{E}$), which are filled as follows:

$$
\begin{align}
    \mathbf{I}_{ij} &= \sum^{n_p}_{k=1}{d_{(k \rightarrow i)jt}} \\
    \mathbf{E}_{ij} &= \sum^{n_p}_{k=1}{d_{(i \rightarrow k)jt}} \\
\end{align}
$$





## Plant replacement

Plant replacements are simulated by dispersing all aphids from replaced plants to
non-replaced plants.
Replaced plants are started at zero for all lines.

## Extinction

I set a threshold for extinction ($\omega$) that defaults to 1.
Any time $N_{ij} < \omega$, $N_{ij}$ is set to zero and listed as extinct.
$N_{ij}$ is ignored until an aphid of line $j$ immigrates to plant $i$.
Increasing $\omega$ to $>1$ could be reasonable given that many---perhaps
most---dispersers die.

