---
title: "Plant death"
author: "Lucas A. Nell"
date: "2018-07-15"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Plant death}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dev = "svglite", 
  fig.width = 6,
  fig.height = 4
)
knitr::opts_knit$set(root.dir = normalizePath(".."))
options(tibble.print_min = 8L, tibble.print_max = 8L)
```
```{r source_Rprofile, echo = FALSE}
if (!isTRUE(getOption('knitr.in.progress'))) source(".Rprofile")
```

```{r library_pkgs, warning=FALSE}
suppressPackageStartupMessages({
    library(clonewars)
    library(lme4)
})
logit <- function(p) {
    suppressWarnings({x <- log(p/(1 - p))})
    x <- ifelse(is.nan(x), NA, x)
    return(x)
}
inv_logit <- function(x) {
    p <- 1 / (1 + exp(-x))
    p <- ifelse(is.na(p) & !is.na(x), 1, p)
    return(p)
}
```



## Looking at when the max is reached

```{r until_max_model}
until_max <- 
    load_data(impute_fxn = impute, filter_pars = NULL) %>%
    mutate(line = paste(line)) %>%
    bind_rows(clonewars:::load_pz_data(impute_fxn = impute, filter_pars = NULL)) %>%
    mutate_at(vars(line, rep), funs(factor)) %>%
    # Now filter out early part of each time series, before N > 6
    # N <= 6 is when the stochasticity associated with only starting with 2 adults
    # appears to be strongest
    # Also filter out until the max is reached, then summarize to see how many days 
    # from N <= 6 to the max N
    group_by(line, rep) %>% 
    filter(1:n() >= which(N > 6)[1],
           1:n() <= which(N == max(N))[1]) %>%
    mutate(date = date - min(date)) %>%
    summarize(days = max(date)) %>% 
    ungroup()

# Original version:
# until_max <- load_data(noNA = FALSE, filter_pars = NULL, remove_unfinished = TRUE) %>%
#     mutate(rep = factor(rep)) %>% 
#     group_by(line, rep) %>%
#     filter(1:n() <= which(N == max(N))[1]) %>%
#     summarize(days = max(date)) %>% 
#     ungroup() %>%
#     identity()

until_max %>% 
    ggplot(aes(line, days, color = line)) +
    scale_color_brewer(palette = "Dark2", guide = FALSE) +
    geom_point()

until_max %>% 
    ggplot(aes(days)) +
    geom_histogram(bins = 10)

until_max_summ <- until_max %>% 
    summarize(max_mean = mean(days),
              max_sd = sd(days))
```




## Looking at mortality after max is reached

```{r after_max_data}
after_max <- load_data(filter_pars = NULL, impute_fxn = impute) %>% 
    mutate(rep = factor(rep)) %>% 
    group_by(line, rep) %>%
    filter(1:n() >= which(N == max(N))[1]) %>%
    mutate(N_ratio = N / lag(N),
           date = date - min(date),
           N_ratio_ = N / N[1],
           N_dead = lag(N) - N) %>% 
    ungroup() %>% 
    filter(!is.na(N_ratio))
```

Exploring data (not evaluated):

```{r after_max_plots, eval = FALSE}
after_max %>%
    ggplot(aes(date, N_ratio)) +
    geom_line(aes(color = rep)) +
    scale_color_brewer(palette = "Dark2", guide = FALSE) +
    facet_wrap(~ line, nrow = 2) +
    NULL


after_max %>%
    filter(N_ratio < 1) %>%
    ggplot(aes(date, logit(N_ratio))) +
    # ggplot(aes(date, N_ratio_)) +
    # geom_point(aes(color = line)) +
    geom_line(aes(color = line, linetype = rep), alpha = 0.5) +
    stat_summary(fun.y = mean, geom = "point", size = 4, shape = 1) +
    stat_smooth(method = "lm", se = FALSE) +
    scale_color_brewer(palette = "Dark2", guide = FALSE) +
        scale_linetype_manual(guide = FALSE, values = 1:7) +
    NULL



after_max %>%
    ggplot(aes(date, N_ratio_)) +
    geom_line(aes(color = line, linetype = rep), alpha = 0.5) +
    stat_summary(fun.y = mean, geom = "point", size = 4, shape = 1) +
    stat_smooth(method = "lm", se = FALSE) +
    scale_color_brewer(palette = "Dark2", guide = FALSE) +
    scale_linetype_manual(guide = FALSE, values = 1:7) +
    NULL

after_max %>%
    ggplot(aes(N_ratio, color = line)) +
    geom_freqpoly(bins = 10, size = 0.75) +
    scale_color_brewer(palette = "Dark2", guide = FALSE) +
    facet_wrap(~ line, ncol = 2) +
    NULL
```

```{r after_max_model}
# AIC is lower than for other combos of date and line
after_max_mod <- after_max %>% 
    # # Removing rows with negative numbers dead.
    # filter(N_dead >= 0) %>% 
    # Rounding values of N and N_dead when N was imputed:
    mutate_at(vars(N, N_dead), round) %>% 
    # Adjusting any negative N_dead numbers by making N_dead 0 and adding whatever
    # negative amount was in N_dead to N
    mutate(N = ifelse(N_dead < 1, N - N_dead, N),
           N_dead = ifelse(N_dead < 1, 0, N_dead)) %>%
    {glmer(cbind(N, N_dead) ~ date + (date | line), family = "binomial", data = .)}
after_max_mod %>% 
    summary()


after_max %>% 
    group_by(line) %>% 
    summarize(date = list(seq(min(date), max(date), length.out = 100))) %>% 
    ungroup() %>% 
    unnest() %>% 
    mutate(N_ratio = predict(after_max_mod, type = "response", newdata = .)) %>% 
    ggplot(aes(date, N_ratio, color = line)) +
    geom_point(data = after_max, alpha = 0.5, shape = 16) +
    geom_line(size = 0.75) +
    facet_wrap(~ line) +
    scale_color_brewer(palette = "Dark2", guide = FALSE)
```

```{r after_max_coefs}
# Each line's coefficients, with an added row for WI-L4Ø that's just the mean:
after_max_coefs <- after_max_mod %>%
    ranef() %>% 
    .[["line"]] %>% 
    `+`(
        after_max_mod %>%
            fixef() %>% 
            rep(each = after_max_mod@flist %>% .[["line"]] %>% 
                    levels() %>% length()) %>% 
            matrix(ncol = after_max_mod@cnms %>% .[["line"]] %>%
                       length())
    ) %>% 
    set_names(c("inter", "date")) %>% 
    rownames_to_column("line") %>% 
    add_row(line = "WI-L4Ø", inter = mean(.$inter), date = mean(.$date)) %>% 
    # Ordering the same as all other data frames:
    mutate(line = factor(line, levels = levels(until_max$line))) %>% 
    arrange(line)
after_max_coefs %>%
    knitr::kable()
```


```{r make_output}
plant_death <- list(
    until_max_summ = as.data.frame(until_max_summ),
    after_max_mort_coefs = after_max_coefs
)
plant_death
```

```{r save_output, eval = FALSE}
devtools::use_data(plant_death, overwrite = TRUE)
```

