---
title: "Simulate cages"
author: "Lucas A. Nell"
date: "2018-07-03"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Simulate cages}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dev = "svglite", 
  fig.width = 6,
  fig.height = 4
)
knitr::opts_knit$set(root.dir = normalizePath(".."))
options(tibble.print_min = 4L, tibble.print_max = 4L)
```
```{r source_Rprofile, echo = FALSE}
if (!isTRUE(getOption('knitr.in.progress'))) source(".Rprofile")
```

```{r library_pkgs, warning=FALSE}
suppressPackageStartupMessages({
    library(clonewars)
})
```


## Load dataset

```{r load_growth_dataset}
growth <- 
    load_data(impute_fxn = impute) %>%
    mutate(line = paste(line)) %>% 
    bind_rows(clonewars:::load_pz_data(impute_fxn = impute)) %>% 
    mutate_at(vars(line, rep), funs(factor)) %>% 
    # Now filter out early part of each time series, before N > 6
    # N <= 6 is when the stochasticity associated with only starting with 2 adults
    # appears to be strongest
    group_by(line, rep) %>% 
    filter(1:n() >= which(N > 6)[1]) %>%
    mutate(date = date - min(date)) %>%
    ungroup()
```


## Load stan fit data

```{r load_stan_fit_data}
stan_fit <- read_rds("data-raw/stan_fit.rds")
```



```{r}
n_plants <- 16
n_lines <- 8
N_0 <- matrix(rep(48/16, n_lines * n_plants), n_plants, n_lines)
max_t <- 180
R <- apply(rstan::extract(stan_fit, "R", permuted = FALSE), 3, mean) %>%
    as.numeric()
A <- apply(rstan::extract(stan_fit, "A", permuted = FALSE), 3, mean) %>%
    as.numeric()
D_mat <- as.matrix(clonewars::disp_estimates[,-1])
process_error <- apply(rstan::extract(stan_fit, "s_epsilon", permuted = FALSE), 
                       3, mean) %>%
    as.numeric()
plant_mort_0 <- clonewars::plant_death$after_max_mort_coefs$inter
plant_mort_1 <- clonewars::plant_death$after_max_mort_coefs$date
plant_death_age_mean <- clonewars::plant_death$until_max_summ$max_mean
plant_death_age_sd <- clonewars::plant_death$until_max_summ$max_sd
repl_times <- seq(4, max_t, 4) - 1
repl_age <- 3
n_cages <- 100
n_cores <- parallel::detectCores() - 1
```


```{r do_sims}
set.seed(654651984L)
sim_df <- cwsims::sim_cages(n_cages, N_0, max_t, R, A, D_mat, process_error,
                            plant_mort_0, plant_mort_1,
                            plant_death_age_mean, plant_death_age_sd,
                            repl_times, repl_age, n_cores) %>% 
    mutate(X = log(N)) %>%
    identity()

sim_by_cage <- sim_df %>%
    mutate(line = factor(line,
                         levels = seq_along(levels(growth$line)),
                         labels = levels(growth$line)),
           rep = factor(rep)) %>% 
    group_by(rep, line, date) %>% 
    summarize(N = sum(N)) %>% 
    group_by(rep, date) %>% 
    arrange(line) %>% 
    mutate(prop = N / sum(N),
           prop_end = cumsum(prop),
           prop_start = lag(prop_end, default = 0)) %>%
    ungroup() %>% 
    mutate(X = log(N))
```


```{r plot_sims}

# This should have zero rows bc having total extinction makes no sense:
sim_by_cage %>% 
    filter(date == max_t) %>% 
    group_by(rep) %>% 
    summarize(N = sum(N)) %>% 
    ungroup() %>% 
    filter(N == 0)


sim_df %>% 
    mutate_at(vars(plant, line), factor) %>% 
    filter(rep == 53, date < 50) %>% 
    ggplot(aes(date, X)) +
    geom_line(aes(color = line)) +
    facet_wrap(~ plant, nrow = 4) +
    scale_color_brewer("Aphid line:", palette = "Dark2") +
    NULL


sim_by_cage %>% 
    filter(rep %in% sample.int(n_cages, 12)) %>% 
    ggplot(aes(date, N)) +
    # ggplot(aes(date, X)) +
    geom_line(aes(color = line)) +
    facet_wrap(~ rep) +
    scale_color_brewer("Aphid line:", palette = "Dark2") +
    NULL


sim_by_cage %>% 
    filter(rep %in% sample.int(n_cages, 12)) %>% 
    ggplot(aes(date, fill = line)) +
    geom_ribbon(aes(ymin = prop_start, ymax = prop_end), color = NA) +
    facet_wrap(~ rep, nrow = 4) +
    scale_fill_brewer("Aphid line:", palette = "Dark2") +
    NULL


sim_by_cage %>% 
    ggplot(aes(date, prop, color = line)) +
    # ggplot(aes(date, gtools::logit(prop), group = rep, color = line)) +
    geom_line(aes(group = rep), alpha = 0.25) +
    facet_wrap(~ line, ncol = 4) +
    # geom_smooth(method = "loess", se = FALSE, span = 0.4, color = "black", linetype = 2) +
    # stat_summary(geom = "line", fun.y = mean, color = "black", size = 0.5) +
    scale_color_brewer(palette = "Dark2", guide = FALSE) +
    ylab("Relative abundance") +
    xlab("Day") +
    NULL

sim_by_cage %>%
    group_by(rep, date) %>% 
    summarize(H = -sum(prop[prop > 0] * log(prop[prop > 0])),
              N = sum(prop > 0),
              E = H / log(N)) %>% 
    ungroup() %>% 
    ggplot(aes(date, N)) +
    geom_line(aes(group = rep), alpha = 0.25, color = "dodgerblue") +
    NULL


sim_by_cage %>% 
    filter(date == max_t) %>% 
    group_by(line) %>% 
    summarize(n = sum(N > 0)) %>% 
    ggplot(aes(line, color = line)) +
    geom_linerange(aes(ymin = 0, ymax = n), size = 1) +
    geom_point(aes(y = n), size = 3) +
    scale_color_brewer(palette = "Dark2", guide = FALSE) +
    ylab("Number of times survived") +
    xlab(NULL) +
    coord_flip() +
    NULL

sim_by_cage %>% 
    filter(date == max_t) %>% 
    group_by(line) %>% 
    summarize(n = sum(prop == 1)) %>% 
    ggplot(aes(line, color = line)) +
    geom_linerange(aes(ymin = 0, ymax = n), size = 1) +
    geom_point(aes(y = n), size = 3) +
    scale_color_brewer(palette = "Dark2", guide = FALSE) +
    ylab("Number of times as sole survivor") +
    xlab(NULL) +
    coord_flip() +
    NULL


sim_by_cage %>% 
    filter(date == max_t) %>% 
    group_by(rep) %>% 
    summarize(n_lines = sum(N > 0)) %>% 
    group_by(n_lines) %>% 
    summarize(n = n())


coexist_reps <- sim_by_cage %>% 
    filter(date == max_t) %>% 
    group_by(rep) %>% 
    summarize(n_lines = sum(N > 0)) %>% 
    filter(n_lines > 1) %>% 
    .[["rep"]]



sim_by_cage %>% 
    filter(rep %in% coexist_reps) %>% 
    ggplot(aes(date, fill = line)) +
    geom_ribbon(aes(ymin = prop_start, ymax = prop_end), color = NA) +
    facet_wrap(~ rep, nrow = 6) +
    scale_fill_brewer("Aphid line:", palette = "Dark2") +
    NULL


# Below only works if the max # remaining lines is 2:

sim_by_cage %>% 
    filter(rep %in% coexist_reps, date == max_t, N > 0) %>% 
    group_by(rep) %>% 
    arrange(line) %>% 
    summarize(l1 = list(line[1:2]), l2 = list(line[2:1])) %>% 
    unnest() %>% 
    ggplot(aes(l1, l2)) +
    geom_abline(slope = 1, intercept = 0, color = "gray60") +
    geom_point(position = position_jitter(width = 0.1, height = 0.1)) +
    theme(panel.grid.major = element_line(color = "gray90")) +
    scale_x_discrete(NULL, drop = FALSE) +
    scale_y_discrete(NULL, drop = FALSE) +
    NULL

```

