source(".Rprofile")
suppressPackageStartupMessages({
    library(clonewars)
})

ggplot2::theme_set(
    theme_bw(base_family = "Helvetica", base_size = 12) +
        theme(plot.background = element_blank(),
              panel.grid = element_blank(),
              panel.background = element_blank(),
              panel.border = element_blank(),
              axis.line = element_line(size = 0.4),
              axis.ticks = element_line(size = 0.3),
              strip.background = element_blank(),
              strip.text = element_text(size = rel(0.9)),
              strip.placement = "outside",
              panel.spacing = unit(1.5, "lines"),
              legend.position = "right",
              legend.background = element_blank(),
              legend.text = element_text(size = 13),
              legend.text.align = 0,
              legend.key = element_blank())
)

# Palette generated by Material Palette - materialpalette.com/blue/deep-orange
palette <- list(
    dark_primary    = "#1976D2",
    default_primary = "#2196F3",
    light_primary   = "#BBDEFB",
    text_primary    = "#FFFFFF",
    accent          = "#FF5722",
    primary_text    = "#212121",
    secondary_text  = "#757575",
    divider         = "#BDBDBD"
)


growth <-
    load_data(impute_fxn = impute, filter_pars = NULL) %>%
    mutate(line = paste(line)) %>%
    bind_rows(clonewars:::load_pz_data(impute_fxn = impute, filter_pars = NULL)) %>%
    mutate_at(vars(line, rep), funs(factor)) %>%
    # Now filter out early part of each time series, before N > 6
    # N <= 6 is when the stochasticity associated with only starting with 2 adults
    # appears to be strongest
    group_by(line, rep) %>%
    filter(1:n() >= which(N > 6)[1]) %>%
    mutate(date = date - min(date),
           disp = ifelse(is.na(disp), 0, disp),
           N = round(N),
           X = log(N),
           pN = N - disp,  # numbers of aphids on plant
           dD = disp - lag(disp, default = 0), # number of new dispersed aphids
           dD = ifelse(dD < 0, 0, dD)) %>%
    ungroup()


reps <- growth %>%
    filter(line == "WI-2016-593") %>%
    .[["rep"]] %>%
    unique() %>%
    paste() %>%
    identity()

example_ts <- lapply(c(reps, reps[1:3]),
       function(r) {
           growth %>%
               filter(line == "WI-2016-593", rep == r) %>%
               dplyr::select(line, rep, date, N, dD) %>%
               ggplot(aes(date)) +
               geom_line(aes(y = N), size = 1.5, color = palette$default_primary) +
               geom_line(aes(y = dD * 20), size = 1.5, color = palette$accent) +
               xlab(NULL) +
               scale_y_continuous(NULL, limits = c(0, 740),
                                  sec.axis = sec_axis(~ . / 20,
                                                      name = NULL)) +
               theme(axis.line = element_blank(), axis.ticks = element_blank(),
                     axis.text = element_blank(), axis.title = element_blank())
       })

for (i in 1:length(example_ts)) {
    fn <- sprintf("figs/growth_ts_%02i.pdf", i)
    ggsave(filename = fn, plot = example_ts[[i]],
           width = 8, height = 8, units = "cm", bg = "white")
}
