/*
    clonewars is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    clonewars is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with clonewars.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.17.0

#include <stan/model/model_header.hpp>

namespace model_full_model_plant_death_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

typedef Eigen::Matrix<double,Eigen::Dynamic,1> vector_d;
typedef Eigen::Matrix<double,1,Eigen::Dynamic> row_vector_d;
typedef Eigen::Matrix<double,Eigen::Dynamic,Eigen::Dynamic> matrix_d;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_full_model_plant_death");
    reader.add_event(174, 174, "end", "model_full_model_plant_death");
    return reader;
}

template <typename T0__, typename T3__, typename T4__, typename T5__, typename T6__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T3__, T4__, T5__, typename boost::math::tools::promote_args<T6__>::type>::type, Eigen::Dynamic,1>
ricker_hat(const Eigen::Matrix<T0__, Eigen::Dynamic,1>& X,
               const int& start,
               const int& end,
               const T3__& r_,
               const Eigen::Matrix<T4__, Eigen::Dynamic,1>& a_,
               const T5__& mu_,
               const T6__& tau_, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T3__, T4__, T5__, typename boost::math::tools::promote_args<T6__>::type>::type fun_scalar_t__;
    typedef fun_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        fun_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 19;
        validate_non_negative_index("X_out", "((end - start) + 1)", ((end - start) + 1));
        Eigen::Matrix<fun_scalar_t__,Eigen::Dynamic,1>  X_out(static_cast<Eigen::VectorXd::Index>(((end - start) + 1)));
        (void) X_out;  // dummy to suppress unused var warning

        stan::math::initialize(X_out, std::numeric_limits<double>::quiet_NaN());
        stan::math::fill(X_out,DUMMY_VAR__);


        current_statement_begin__ = 20;
        stan::math::assign(get_base1_lhs(X_out,1,"X_out",1), get_base1(X,start,"X",1));
        current_statement_begin__ = 21;
        stan::model::assign(X_out, 
                    stan::model::cons_list(stan::model::index_min_max(2, ((end - start) + 1)), stan::model::nil_index_list()), 
                    add(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_min_max(start, (end - 1)), stan::model::nil_index_list()), "X"),multiply(r_,subtract(1,elt_multiply(a_,exp(add(multiply(tau_,stan::model::rvalue(X, stan::model::cons_list(stan::model::index_min_max(start, (end - 1)), stan::model::nil_index_list()), "X")),mu_)))))), 
                    "assigning variable X_out");
        current_statement_begin__ = 23;
        return stan::math::promote_scalar<fun_return_scalar_t__>(X_out);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct ricker_hat_functor__ {
    template <typename T0__, typename T3__, typename T4__, typename T5__, typename T6__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T3__, T4__, T5__, typename boost::math::tools::promote_args<T6__>::type>::type, Eigen::Dynamic,1>
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic,1>& X,
               const int& start,
               const int& end,
               const T3__& r_,
               const Eigen::Matrix<T4__, Eigen::Dynamic,1>& a_,
               const T5__& mu_,
               const T6__& tau_, std::ostream* pstream__) const {
        return ricker_hat(X, start, end, r_, a_, mu_, tau_, pstream__);
    }
};

#include <meta_header.hpp>
 class model_full_model_plant_death : public prob_grad {
private:
    int n_ts;
    int n_obs;
    vector<int> n_per;
    vector_d X;
    int n_lines;
    vector<int> L;
    vector_d X_hat;
    vector_d N_bar_hat;
    double mu;
    double tau;
    vector<double> theta;
public:
    model_full_model_plant_death(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }

    model_full_model_plant_death(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "model_full_model_plant_death_namespace::model_full_model_plant_death";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        // initialize member variables
        try {
            current_statement_begin__ = 29;
            context__.validate_dims("data initialization", "n_ts", "int", context__.to_vec());
            n_ts = int(0);
            vals_i__ = context__.vals_i("n_ts");
            pos__ = 0;
            n_ts = vals_i__[pos__++];
            current_statement_begin__ = 30;
            context__.validate_dims("data initialization", "n_obs", "int", context__.to_vec());
            n_obs = int(0);
            vals_i__ = context__.vals_i("n_obs");
            pos__ = 0;
            n_obs = vals_i__[pos__++];
            current_statement_begin__ = 31;
            validate_non_negative_index("n_per", "n_ts", n_ts);
            context__.validate_dims("data initialization", "n_per", "int", context__.to_vec(n_ts));
            validate_non_negative_index("n_per", "n_ts", n_ts);
            n_per = std::vector<int>(n_ts,int(0));
            vals_i__ = context__.vals_i("n_per");
            pos__ = 0;
            size_t n_per_limit_0__ = n_ts;
            for (size_t i_0__ = 0; i_0__ < n_per_limit_0__; ++i_0__) {
                n_per[i_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 34;
            validate_non_negative_index("X", "n_obs", n_obs);
            context__.validate_dims("data initialization", "X", "vector_d", context__.to_vec(n_obs));
            validate_non_negative_index("X", "n_obs", n_obs);
            X = vector_d(static_cast<Eigen::VectorXd::Index>(n_obs));
            vals_r__ = context__.vals_r("X");
            pos__ = 0;
            size_t X_i_vec_lim__ = n_obs;
            for (size_t i_vec__ = 0; i_vec__ < X_i_vec_lim__; ++i_vec__) {
                X[i_vec__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 36;
            context__.validate_dims("data initialization", "n_lines", "int", context__.to_vec());
            n_lines = int(0);
            vals_i__ = context__.vals_i("n_lines");
            pos__ = 0;
            n_lines = vals_i__[pos__++];
            current_statement_begin__ = 37;
            validate_non_negative_index("L", "n_ts", n_ts);
            context__.validate_dims("data initialization", "L", "int", context__.to_vec(n_ts));
            validate_non_negative_index("L", "n_ts", n_ts);
            L = std::vector<int>(n_ts,int(0));
            vals_i__ = context__.vals_i("L");
            pos__ = 0;
            size_t L_limit_0__ = n_ts;
            for (size_t i_0__ = 0; i_0__ < L_limit_0__; ++i_0__) {
                L[i_0__] = vals_i__[pos__++];
            }

            // validate, data variables
            current_statement_begin__ = 29;
            check_greater_or_equal(function__,"n_ts",n_ts,1);
            current_statement_begin__ = 30;
            check_greater_or_equal(function__,"n_obs",n_obs,1);
            current_statement_begin__ = 31;
            for (int k0__ = 0; k0__ < n_ts; ++k0__) {
                check_greater_or_equal(function__,"n_per[k0__]",n_per[k0__],1);
            }
            current_statement_begin__ = 34;
            check_greater_or_equal(function__,"X",X,0);
            current_statement_begin__ = 36;
            check_greater_or_equal(function__,"n_lines",n_lines,1);
            current_statement_begin__ = 37;
            for (int k0__ = 0; k0__ < n_ts; ++k0__) {
                check_greater_or_equal(function__,"L[k0__]",L[k0__],1);
                check_less_or_equal(function__,"L[k0__]",L[k0__],n_lines);
            }
            // initialize data variables
            current_statement_begin__ = 42;
            validate_non_negative_index("X_hat", "n_obs", n_obs);
            X_hat = vector_d(static_cast<Eigen::VectorXd::Index>(n_obs));
            stan::math::fill(X_hat,DUMMY_VAR__);
            current_statement_begin__ = 43;
            validate_non_negative_index("N_bar_hat", "n_obs", n_obs);
            N_bar_hat = vector_d(static_cast<Eigen::VectorXd::Index>(n_obs));
            stan::math::fill(N_bar_hat,DUMMY_VAR__);
            current_statement_begin__ = 44;
            mu = double(0);
            stan::math::fill(mu,DUMMY_VAR__);
            current_statement_begin__ = 45;
            tau = double(0);
            stan::math::fill(tau,DUMMY_VAR__);
            current_statement_begin__ = 46;
            validate_non_negative_index("theta", "12", 12);
            theta = std::vector<double>(12,double(0));
            stan::math::fill(theta,DUMMY_VAR__);
            stan::math::assign(theta,rep_array(0.0,12));

            current_statement_begin__ = 48;
            for (int i = 1; i <= 6; ++i) {
                current_statement_begin__ = 48;
                stan::math::assign(get_base1_lhs(theta,(i * 2),"theta",1), 1);
            }
            current_statement_begin__ = 50;
            stan::math::assign(mu, mean(X));
            current_statement_begin__ = 51;
            stan::math::assign(tau, sd(X));
            current_statement_begin__ = 53;
            stan::math::assign(X_hat, divide(subtract(X,mu),tau));
            {
            current_statement_begin__ = 58;
            int t(0);
            (void) t;  // dummy to suppress unused var warning

            stan::math::fill(t, std::numeric_limits<int>::min());
            stan::math::assign(t,1);
            current_statement_begin__ = 59;
            validate_non_negative_index("N", "n_obs", n_obs);
            vector_d N(static_cast<Eigen::VectorXd::Index>(n_obs));
            (void) N;  // dummy to suppress unused var warning

            stan::math::initialize(N, std::numeric_limits<double>::quiet_NaN());
            stan::math::fill(N,DUMMY_VAR__);
            stan::math::assign(N,exp(X));
            current_statement_begin__ = 60;
            validate_non_negative_index("N_bar", "n_obs", n_obs);
            vector_d N_bar(static_cast<Eigen::VectorXd::Index>(n_obs));
            (void) N_bar;  // dummy to suppress unused var warning

            stan::math::initialize(N_bar, std::numeric_limits<double>::quiet_NaN());
            stan::math::fill(N_bar,DUMMY_VAR__);
            current_statement_begin__ = 61;
            double mu_(0.0);
            (void) mu_;  // dummy to suppress unused var warning

            stan::math::initialize(mu_, std::numeric_limits<double>::quiet_NaN());
            stan::math::fill(mu_,DUMMY_VAR__);
            current_statement_begin__ = 62;
            double tau_(0.0);
            (void) tau_;  // dummy to suppress unused var warning

            stan::math::initialize(tau_, std::numeric_limits<double>::quiet_NaN());
            stan::math::fill(tau_,DUMMY_VAR__);


            current_statement_begin__ = 63;
            stan::math::assign(mu_, mean(N));
            current_statement_begin__ = 64;
            stan::math::assign(tau_, sd(N));
            current_statement_begin__ = 65;
            stan::math::assign(N_bar, divide(subtract(N,mu_),tau_));
            current_statement_begin__ = 66;
            for (int j = 1; j <= n_ts; ++j) {
                {
                current_statement_begin__ = 68;
                int end(0);
                (void) end;  // dummy to suppress unused var warning

                stan::math::fill(end, std::numeric_limits<int>::min());
                stan::math::assign(end,((t + get_base1(n_per,j,"n_per",1)) - 1));


                current_statement_begin__ = 69;
                stan::math::assign(get_base1_lhs(N_bar_hat,t,"N_bar_hat",1), 0);
                current_statement_begin__ = 70;
                stan::math::assign(t, (t + 1));
                current_statement_begin__ = 72;
                while (as_bool(logical_lte(t,end))) {

                    current_statement_begin__ = 73;
                    stan::math::assign(get_base1_lhs(N_bar_hat,t,"N_bar_hat",1), (get_base1(N_bar_hat,(t - 1),"N_bar_hat",1) + get_base1(N_bar,(t - 1),"N_bar",1)));
                    current_statement_begin__ = 74;
                    stan::math::assign(t, (t + 1));
                }
                }
            }
            }

            // validate transformed data
            current_statement_begin__ = 42;
            current_statement_begin__ = 43;
            current_statement_begin__ = 44;
            current_statement_begin__ = 45;
            current_statement_begin__ = 46;

            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 84;
            validate_non_negative_index("Z_r", "n_lines", n_lines);
            num_params_r__ += n_lines;
            current_statement_begin__ = 85;
            validate_non_negative_index("Z_alpha_l", "n_lines", n_lines);
            num_params_r__ += n_lines;
            current_statement_begin__ = 88;
            ++num_params_r__;
            current_statement_begin__ = 90;
            ++num_params_r__;
            current_statement_begin__ = 91;
            ++num_params_r__;
            current_statement_begin__ = 92;
            ++num_params_r__;
            current_statement_begin__ = 93;
            ++num_params_r__;
            current_statement_begin__ = 96;
            ++num_params_r__;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    ~model_full_model_plant_death() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        if (!(context__.contains_r("Z_r")))
            throw std::runtime_error("variable Z_r missing");
        vals_r__ = context__.vals_r("Z_r");
        pos__ = 0U;
        validate_non_negative_index("Z_r", "n_lines", n_lines);
        context__.validate_dims("initialization", "Z_r", "vector_d", context__.to_vec(n_lines));
        vector_d Z_r(static_cast<Eigen::VectorXd::Index>(n_lines));
        for (int j1__ = 0U; j1__ < n_lines; ++j1__)
            Z_r(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_unconstrain(Z_r);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable Z_r: ") + e.what());
        }

        if (!(context__.contains_r("Z_alpha_l")))
            throw std::runtime_error("variable Z_alpha_l missing");
        vals_r__ = context__.vals_r("Z_alpha_l");
        pos__ = 0U;
        validate_non_negative_index("Z_alpha_l", "n_lines", n_lines);
        context__.validate_dims("initialization", "Z_alpha_l", "vector_d", context__.to_vec(n_lines));
        vector_d Z_alpha_l(static_cast<Eigen::VectorXd::Index>(n_lines));
        for (int j1__ = 0U; j1__ < n_lines; ++j1__)
            Z_alpha_l(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_unconstrain(Z_alpha_l);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable Z_alpha_l: ") + e.what());
        }

        if (!(context__.contains_r("hat_sigma_epsilon")))
            throw std::runtime_error("variable hat_sigma_epsilon missing");
        vals_r__ = context__.vals_r("hat_sigma_epsilon");
        pos__ = 0U;
        context__.validate_dims("initialization", "hat_sigma_epsilon", "double", context__.to_vec());
        double hat_sigma_epsilon(0);
        hat_sigma_epsilon = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,hat_sigma_epsilon);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable hat_sigma_epsilon: ") + e.what());
        }

        if (!(context__.contains_r("rho")))
            throw std::runtime_error("variable rho missing");
        vals_r__ = context__.vals_r("rho");
        pos__ = 0U;
        context__.validate_dims("initialization", "rho", "double", context__.to_vec());
        double rho(0);
        rho = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(rho);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable rho: ") + e.what());
        }

        if (!(context__.contains_r("hat_sigma_rho")))
            throw std::runtime_error("variable hat_sigma_rho missing");
        vals_r__ = context__.vals_r("hat_sigma_rho");
        pos__ = 0U;
        context__.validate_dims("initialization", "hat_sigma_rho", "double", context__.to_vec());
        double hat_sigma_rho(0);
        hat_sigma_rho = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,hat_sigma_rho);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable hat_sigma_rho: ") + e.what());
        }

        if (!(context__.contains_r("phi")))
            throw std::runtime_error("variable phi missing");
        vals_r__ = context__.vals_r("phi");
        pos__ = 0U;
        context__.validate_dims("initialization", "phi", "double", context__.to_vec());
        double phi(0);
        phi = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(phi);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable phi: ") + e.what());
        }

        if (!(context__.contains_r("hat_sigma_phi_l")))
            throw std::runtime_error("variable hat_sigma_phi_l missing");
        vals_r__ = context__.vals_r("hat_sigma_phi_l");
        pos__ = 0U;
        context__.validate_dims("initialization", "hat_sigma_phi_l", "double", context__.to_vec());
        double hat_sigma_phi_l(0);
        hat_sigma_phi_l = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,hat_sigma_phi_l);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable hat_sigma_phi_l: ") + e.what());
        }

        if (!(context__.contains_r("b_hat")))
            throw std::runtime_error("variable b_hat missing");
        vals_r__ = context__.vals_r("b_hat");
        pos__ = 0U;
        context__.validate_dims("initialization", "b_hat", "double", context__.to_vec());
        double b_hat(0);
        b_hat = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,b_hat);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable b_hat: ") + e.what());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        T__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;

        try {
            // model parameters
            stan::io::reader<T__> in__(params_r__,params_i__);

            Eigen::Matrix<T__,Eigen::Dynamic,1>  Z_r;
            (void) Z_r;  // dummy to suppress unused var warning
            if (jacobian__)
                Z_r = in__.vector_constrain(n_lines,lp__);
            else
                Z_r = in__.vector_constrain(n_lines);

            Eigen::Matrix<T__,Eigen::Dynamic,1>  Z_alpha_l;
            (void) Z_alpha_l;  // dummy to suppress unused var warning
            if (jacobian__)
                Z_alpha_l = in__.vector_constrain(n_lines,lp__);
            else
                Z_alpha_l = in__.vector_constrain(n_lines);

            T__ hat_sigma_epsilon;
            (void) hat_sigma_epsilon;  // dummy to suppress unused var warning
            if (jacobian__)
                hat_sigma_epsilon = in__.scalar_lb_constrain(0,lp__);
            else
                hat_sigma_epsilon = in__.scalar_lb_constrain(0);

            T__ rho;
            (void) rho;  // dummy to suppress unused var warning
            if (jacobian__)
                rho = in__.scalar_constrain(lp__);
            else
                rho = in__.scalar_constrain();

            T__ hat_sigma_rho;
            (void) hat_sigma_rho;  // dummy to suppress unused var warning
            if (jacobian__)
                hat_sigma_rho = in__.scalar_lb_constrain(0,lp__);
            else
                hat_sigma_rho = in__.scalar_lb_constrain(0);

            T__ phi;
            (void) phi;  // dummy to suppress unused var warning
            if (jacobian__)
                phi = in__.scalar_constrain(lp__);
            else
                phi = in__.scalar_constrain();

            T__ hat_sigma_phi_l;
            (void) hat_sigma_phi_l;  // dummy to suppress unused var warning
            if (jacobian__)
                hat_sigma_phi_l = in__.scalar_lb_constrain(0,lp__);
            else
                hat_sigma_phi_l = in__.scalar_lb_constrain(0);

            T__ b_hat;
            (void) b_hat;  // dummy to suppress unused var warning
            if (jacobian__)
                b_hat = in__.scalar_lb_constrain(0,lp__);
            else
                b_hat = in__.scalar_lb_constrain(0);


            // transformed parameters
            current_statement_begin__ = 101;
            validate_non_negative_index("X_hat_pred", "n_obs", n_obs);
            Eigen::Matrix<T__,Eigen::Dynamic,1>  X_hat_pred(static_cast<Eigen::VectorXd::Index>(n_obs));
            (void) X_hat_pred;  // dummy to suppress unused var warning

            stan::math::initialize(X_hat_pred, DUMMY_VAR__);
            stan::math::fill(X_hat_pred,DUMMY_VAR__);


            {
            current_statement_begin__ = 105;
            int start(0);
            (void) start;  // dummy to suppress unused var warning

            stan::math::fill(start, std::numeric_limits<int>::min());
            stan::math::assign(start,1);


            current_statement_begin__ = 106;
            for (int j = 1; j <= n_ts; ++j) {
                {
                current_statement_begin__ = 108;
                int n_(0);
                (void) n_;  // dummy to suppress unused var warning

                stan::math::fill(n_, std::numeric_limits<int>::min());
                stan::math::assign(n_,get_base1(n_per,j,"n_per",1));
                current_statement_begin__ = 109;
                int end(0);
                (void) end;  // dummy to suppress unused var warning

                stan::math::fill(end, std::numeric_limits<int>::min());
                stan::math::assign(end,((start + n_) - 1));
                current_statement_begin__ = 111;
                T__ r_hat;
                (void) r_hat;  // dummy to suppress unused var warning

                stan::math::initialize(r_hat, DUMMY_VAR__);
                stan::math::fill(r_hat,DUMMY_VAR__);
                stan::math::assign(r_hat,exp((rho + (hat_sigma_rho * get_base1(Z_r,get_base1(L,j,"L",1),"Z_r",1)))));
                current_statement_begin__ = 113;
                validate_non_negative_index("alpha_hat", "(n_ - 1)", (n_ - 1));
                Eigen::Matrix<T__,Eigen::Dynamic,1>  alpha_hat(static_cast<Eigen::VectorXd::Index>((n_ - 1)));
                (void) alpha_hat;  // dummy to suppress unused var warning

                stan::math::initialize(alpha_hat, DUMMY_VAR__);
                stan::math::fill(alpha_hat,DUMMY_VAR__);
                stan::math::assign(alpha_hat,exp(add((phi + (hat_sigma_phi_l * get_base1(Z_alpha_l,get_base1(L,j,"L",1),"Z_alpha_l",1))),multiply(b_hat,stan::model::rvalue(N_bar_hat, stan::model::cons_list(stan::model::index_min_max((start + 1), end), stan::model::nil_index_list()), "N_bar_hat")))));


                current_statement_begin__ = 116;
                stan::model::assign(X_hat_pred, 
                            stan::model::cons_list(stan::model::index_min_max(start, end), stan::model::nil_index_list()), 
                            ricker_hat(X_hat,start,end,r_hat,alpha_hat,mu,tau, pstream__), 
                            "assigning variable X_hat_pred");
                current_statement_begin__ = 119;
                stan::math::assign(start, (start + n_));
                }
            }
            }

            // validate transformed parameters
            for (int i0__ = 0; i0__ < n_obs; ++i0__) {
                if (stan::math::is_uninitialized(X_hat_pred(i0__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: X_hat_pred" << '[' << i0__ << ']';
                    throw std::runtime_error(msg__.str());
                }
            }

            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 101;

            // model body

            current_statement_begin__ = 127;
            lp_accum__.add(normal_log<propto__>(Z_r, 0, 1));
            current_statement_begin__ = 128;
            lp_accum__.add(normal_log<propto__>(Z_alpha_l, 0, 1));
            current_statement_begin__ = 131;
            lp_accum__.add(normal_log<propto__>(hat_sigma_epsilon, get_base1(theta,1,"theta",1), get_base1(theta,2,"theta",1)));
            if (hat_sigma_epsilon < 0) lp_accum__.add(-std::numeric_limits<double>::infinity());
            else lp_accum__.add(-normal_ccdf_log(0, get_base1(theta,1,"theta",1), get_base1(theta,2,"theta",1)));
            current_statement_begin__ = 132;
            lp_accum__.add(normal_log<propto__>(rho, get_base1(theta,3,"theta",1), get_base1(theta,4,"theta",1)));
            current_statement_begin__ = 133;
            lp_accum__.add(normal_log<propto__>(hat_sigma_rho, get_base1(theta,5,"theta",1), get_base1(theta,6,"theta",1)));
            if (hat_sigma_rho < 0) lp_accum__.add(-std::numeric_limits<double>::infinity());
            else lp_accum__.add(-normal_ccdf_log(0, get_base1(theta,5,"theta",1), get_base1(theta,6,"theta",1)));
            current_statement_begin__ = 134;
            lp_accum__.add(normal_log<propto__>(phi, get_base1(theta,7,"theta",1), get_base1(theta,8,"theta",1)));
            current_statement_begin__ = 135;
            lp_accum__.add(normal_log<propto__>(hat_sigma_phi_l, get_base1(theta,9,"theta",1), get_base1(theta,10,"theta",1)));
            if (hat_sigma_phi_l < 0) lp_accum__.add(-std::numeric_limits<double>::infinity());
            else lp_accum__.add(-normal_ccdf_log(0, get_base1(theta,9,"theta",1), get_base1(theta,10,"theta",1)));
            current_statement_begin__ = 138;
            lp_accum__.add(normal_log<propto__>(b_hat, 0, 1));
            if (b_hat < 0) lp_accum__.add(-std::numeric_limits<double>::infinity());
            else lp_accum__.add(-normal_ccdf_log(0, 0, 1));
            {
            current_statement_begin__ = 143;
            int start(0);
            (void) start;  // dummy to suppress unused var warning

            stan::math::fill(start, std::numeric_limits<int>::min());
            stan::math::assign(start,1);


            current_statement_begin__ = 144;
            for (int j = 1; j <= n_ts; ++j) {
                {
                current_statement_begin__ = 146;
                int n_(0);
                (void) n_;  // dummy to suppress unused var warning

                stan::math::fill(n_, std::numeric_limits<int>::min());
                stan::math::assign(n_,get_base1(n_per,j,"n_per",1));
                current_statement_begin__ = 147;
                int end(0);
                (void) end;  // dummy to suppress unused var warning

                stan::math::fill(end, std::numeric_limits<int>::min());
                stan::math::assign(end,((start + n_) - 1));


                current_statement_begin__ = 148;
                lp_accum__.add(normal_log<propto__>(stan::model::rvalue(X_hat, stan::model::cons_list(stan::model::index_min_max((start + 1), end), stan::model::nil_index_list()), "X_hat"), stan::model::rvalue(X_hat_pred, stan::model::cons_list(stan::model::index_min_max((start + 1), end), stan::model::nil_index_list()), "X_hat_pred"), hat_sigma_epsilon));
                current_statement_begin__ = 150;
                stan::math::assign(start, (start + n_));
                }
            }
            }

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("Z_r");
        names__.push_back("Z_alpha_l");
        names__.push_back("hat_sigma_epsilon");
        names__.push_back("rho");
        names__.push_back("hat_sigma_rho");
        names__.push_back("phi");
        names__.push_back("hat_sigma_phi_l");
        names__.push_back("b_hat");
        names__.push_back("X_hat_pred");
        names__.push_back("X_resid");
        names__.push_back("X_pred");
        names__.push_back("R");
        names__.push_back("A");
        names__.push_back("sigma_epsilon");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(n_lines);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_lines);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_obs);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_obs);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_obs);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_lines);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_lines);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        vars__.resize(0);
        stan::io::reader<double> in__(params_r__,params_i__);
        static const char* function__ = "model_full_model_plant_death_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        vector_d Z_r = in__.vector_constrain(n_lines);
        vector_d Z_alpha_l = in__.vector_constrain(n_lines);
        double hat_sigma_epsilon = in__.scalar_lb_constrain(0);
        double rho = in__.scalar_constrain();
        double hat_sigma_rho = in__.scalar_lb_constrain(0);
        double phi = in__.scalar_constrain();
        double hat_sigma_phi_l = in__.scalar_lb_constrain(0);
        double b_hat = in__.scalar_lb_constrain(0);
            for (int k_0__ = 0; k_0__ < n_lines; ++k_0__) {
            vars__.push_back(Z_r[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < n_lines; ++k_0__) {
            vars__.push_back(Z_alpha_l[k_0__]);
            }
        vars__.push_back(hat_sigma_epsilon);
        vars__.push_back(rho);
        vars__.push_back(hat_sigma_rho);
        vars__.push_back(phi);
        vars__.push_back(hat_sigma_phi_l);
        vars__.push_back(b_hat);

        if (!include_tparams__) return;
        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        try {
            current_statement_begin__ = 101;
            validate_non_negative_index("X_hat_pred", "n_obs", n_obs);
            vector_d X_hat_pred(static_cast<Eigen::VectorXd::Index>(n_obs));
            (void) X_hat_pred;  // dummy to suppress unused var warning

            stan::math::initialize(X_hat_pred, std::numeric_limits<double>::quiet_NaN());
            stan::math::fill(X_hat_pred,DUMMY_VAR__);


            {
            current_statement_begin__ = 105;
            int start(0);
            (void) start;  // dummy to suppress unused var warning

            stan::math::fill(start, std::numeric_limits<int>::min());
            stan::math::assign(start,1);


            current_statement_begin__ = 106;
            for (int j = 1; j <= n_ts; ++j) {
                {
                current_statement_begin__ = 108;
                int n_(0);
                (void) n_;  // dummy to suppress unused var warning

                stan::math::fill(n_, std::numeric_limits<int>::min());
                stan::math::assign(n_,get_base1(n_per,j,"n_per",1));
                current_statement_begin__ = 109;
                int end(0);
                (void) end;  // dummy to suppress unused var warning

                stan::math::fill(end, std::numeric_limits<int>::min());
                stan::math::assign(end,((start + n_) - 1));
                current_statement_begin__ = 111;
                double r_hat(0.0);
                (void) r_hat;  // dummy to suppress unused var warning

                stan::math::initialize(r_hat, std::numeric_limits<double>::quiet_NaN());
                stan::math::fill(r_hat,DUMMY_VAR__);
                stan::math::assign(r_hat,exp((rho + (hat_sigma_rho * get_base1(Z_r,get_base1(L,j,"L",1),"Z_r",1)))));
                current_statement_begin__ = 113;
                validate_non_negative_index("alpha_hat", "(n_ - 1)", (n_ - 1));
                vector_d alpha_hat(static_cast<Eigen::VectorXd::Index>((n_ - 1)));
                (void) alpha_hat;  // dummy to suppress unused var warning

                stan::math::initialize(alpha_hat, std::numeric_limits<double>::quiet_NaN());
                stan::math::fill(alpha_hat,DUMMY_VAR__);
                stan::math::assign(alpha_hat,exp(add((phi + (hat_sigma_phi_l * get_base1(Z_alpha_l,get_base1(L,j,"L",1),"Z_alpha_l",1))),multiply(b_hat,stan::model::rvalue(N_bar_hat, stan::model::cons_list(stan::model::index_min_max((start + 1), end), stan::model::nil_index_list()), "N_bar_hat")))));


                current_statement_begin__ = 116;
                stan::model::assign(X_hat_pred, 
                            stan::model::cons_list(stan::model::index_min_max(start, end), stan::model::nil_index_list()), 
                            ricker_hat(X_hat,start,end,r_hat,alpha_hat,mu,tau, pstream__), 
                            "assigning variable X_hat_pred");
                current_statement_begin__ = 119;
                stan::math::assign(start, (start + n_));
                }
            }
            }

            // validate transformed parameters
            current_statement_begin__ = 101;

            // write transformed parameters
            for (int k_0__ = 0; k_0__ < n_obs; ++k_0__) {
            vars__.push_back(X_hat_pred[k_0__]);
            }

            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 157;
            validate_non_negative_index("X_resid", "n_obs", n_obs);
            vector_d X_resid(static_cast<Eigen::VectorXd::Index>(n_obs));
            (void) X_resid;  // dummy to suppress unused var warning

            stan::math::initialize(X_resid, std::numeric_limits<double>::quiet_NaN());
            stan::math::fill(X_resid,DUMMY_VAR__);
            current_statement_begin__ = 162;
            validate_non_negative_index("X_pred", "n_obs", n_obs);
            vector_d X_pred(static_cast<Eigen::VectorXd::Index>(n_obs));
            (void) X_pred;  // dummy to suppress unused var warning

            stan::math::initialize(X_pred, std::numeric_limits<double>::quiet_NaN());
            stan::math::fill(X_pred,DUMMY_VAR__);
            current_statement_begin__ = 163;
            validate_non_negative_index("R", "n_lines", n_lines);
            vector_d R(static_cast<Eigen::VectorXd::Index>(n_lines));
            (void) R;  // dummy to suppress unused var warning

            stan::math::initialize(R, std::numeric_limits<double>::quiet_NaN());
            stan::math::fill(R,DUMMY_VAR__);
            current_statement_begin__ = 164;
            validate_non_negative_index("A", "n_lines", n_lines);
            vector_d A(static_cast<Eigen::VectorXd::Index>(n_lines));
            (void) A;  // dummy to suppress unused var warning

            stan::math::initialize(A, std::numeric_limits<double>::quiet_NaN());
            stan::math::fill(A,DUMMY_VAR__);
            current_statement_begin__ = 165;
            double sigma_epsilon(0.0);
            (void) sigma_epsilon;  // dummy to suppress unused var warning

            stan::math::initialize(sigma_epsilon, std::numeric_limits<double>::quiet_NaN());
            stan::math::fill(sigma_epsilon,DUMMY_VAR__);


            current_statement_begin__ = 167;
            stan::math::assign(X_resid, subtract(X_hat,X_hat_pred));
            current_statement_begin__ = 169;
            stan::math::assign(X_pred, add(multiply(X_hat_pred,tau),mu));
            current_statement_begin__ = 170;
            stan::math::assign(R, multiply(exp(add(rho,multiply(hat_sigma_rho,Z_r))),tau));
            current_statement_begin__ = 171;
            stan::math::assign(A, exp(add(phi,multiply(hat_sigma_phi_l,Z_alpha_l))));
            current_statement_begin__ = 172;
            stan::math::assign(sigma_epsilon, (hat_sigma_epsilon * tau));

            // validate generated quantities
            current_statement_begin__ = 157;
            current_statement_begin__ = 162;
            current_statement_begin__ = 163;
            current_statement_begin__ = 164;
            current_statement_begin__ = 165;

            // write generated quantities
            for (int k_0__ = 0; k_0__ < n_obs; ++k_0__) {
            vars__.push_back(X_resid[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < n_obs; ++k_0__) {
            vars__.push_back(X_pred[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < n_lines; ++k_0__) {
            vars__.push_back(R[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < n_lines; ++k_0__) {
            vars__.push_back(A[k_0__]);
            }
        vars__.push_back(sigma_epsilon);

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    static std::string model_name() {
        return "model_full_model_plant_death";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= n_lines; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "Z_r" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= n_lines; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "Z_alpha_l" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "hat_sigma_epsilon";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "rho";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "hat_sigma_rho";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "phi";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "hat_sigma_phi_l";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "b_hat";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;
        for (int k_0__ = 1; k_0__ <= n_obs; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "X_hat_pred" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__) return;
        for (int k_0__ = 1; k_0__ <= n_obs; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "X_resid" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= n_obs; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "X_pred" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= n_lines; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "R" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= n_lines; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "A" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma_epsilon";
        param_names__.push_back(param_name_stream__.str());
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= n_lines; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "Z_r" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= n_lines; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "Z_alpha_l" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "hat_sigma_epsilon";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "rho";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "hat_sigma_rho";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "phi";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "hat_sigma_phi_l";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "b_hat";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;
        for (int k_0__ = 1; k_0__ <= n_obs; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "X_hat_pred" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__) return;
        for (int k_0__ = 1; k_0__ <= n_obs; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "X_resid" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= n_obs; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "X_pred" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= n_lines; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "R" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= n_lines; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "A" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma_epsilon";
        param_names__.push_back(param_name_stream__.str());
    }

}; // model

}

typedef model_full_model_plant_death_namespace::model_full_model_plant_death stan_model;


#endif
