// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4full_model_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4full_model_plant_death_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4no_among_alpha_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4no_within_alpha_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4one_alpha_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4one_r_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4one_r_alpha_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4pass_sigma_epsilon_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4full_model_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4full_model_mod, 0},
    {"_rcpp_module_boot_stan_fit4full_model_plant_death_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4full_model_plant_death_mod, 0},
    {"_rcpp_module_boot_stan_fit4no_among_alpha_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4no_among_alpha_mod, 0},
    {"_rcpp_module_boot_stan_fit4no_within_alpha_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4no_within_alpha_mod, 0},
    {"_rcpp_module_boot_stan_fit4one_alpha_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4one_alpha_mod, 0},
    {"_rcpp_module_boot_stan_fit4one_r_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4one_r_mod, 0},
    {"_rcpp_module_boot_stan_fit4one_r_alpha_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4one_r_alpha_mod, 0},
    {"_rcpp_module_boot_stan_fit4pass_sigma_epsilon_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4pass_sigma_epsilon_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_clonewars(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
