# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Logit and inverse logit functions.
#'
#'
#' @export
#'
logit <- function(p) {
    .Call(`_clonewars_logit`, p)
}

#' @describeIn logit
#'
#' @export
#'
inv_logit <- function(a) {
    .Call(`_clonewars_inv_logit`, a)
}

#' Create Leslie matrix from aphid info
#'
#' @param instar_days Integer vector of the number of stages (days) per aphid instar.
#' @param surv_juv Single numeric of daily juvenile survival.
#' @param surv_adult Numeric vector of aphid adult survivals by stage.
#' @param repro Numeric vector of aphid reproductive rates by stage.
#'
#'
#' @export
leslie_matrix <- function(instar_days, surv_juv, surv_adult, repro) {
    .Call(`_clonewars_leslie_matrix`, instar_days, surv_juv, surv_adult, repro)
}

#' Compute the "stable age distribution" from a Leslie matrix
#'
#' @param leslie Leslie matrix of the population.
#'
#' @export
#'
#' @return Vector with the stable age distribution given the Leslie matrix.
#'
sad_leslie <- function(leslie) {
    .Call(`_clonewars_sad_leslie`, leslie)
}

#' Calculate the number of rows per rep.
#'
#' @noRd
#'
NULL

#' Simulate multiple reps.
#'
#'
#' @inheritParams sim_reps
#'
#' @noRd
#'
#'
NULL

#' Check that the number of threads doesn't exceed the number available, and change
#' to 1 if OpenMP isn't enabled.
#'
#' @noRd
#'
NULL

sim_clonewars_cpp <- function(n_reps, max_plant_age, max_N, check_for_clear, max_t, save_every, mean_K, sd_K, meanlog_death_age, sdlog_death_age, shape1_death_mort, shape2_death_mort, disp_error, demog_error, sigma_x, rho, extinct_N, aphid_name, leslie_mat, aphid_density_0, alate_prop, disp_rate, disp_mort, disp_start, pred_rate, n_threads, show_progress) {
    .Call(`_clonewars_sim_clonewars_cpp`, n_reps, max_plant_age, max_N, check_for_clear, max_t, save_every, mean_K, sd_K, meanlog_death_age, sdlog_death_age, shape1_death_mort, shape2_death_mort, disp_error, demog_error, sigma_x, rho, extinct_N, aphid_name, leslie_mat, aphid_density_0, alate_prop, disp_rate, disp_mort, disp_start, pred_rate, n_threads, show_progress)
}

